### ISSUE TITLE
[develop] Attribute devices

### ISSUE THREAD

**Issue by overload08** [domogik/domogik-brain-core#3]
Whe I say "est-ce que cuisine est allumé ?", logs returns "ERROR RS : Error executing Python object: 'RiveScript' object has no attribute 'devices'" and Buttler always says "Yes"

**Comment by fritz-smh** [comment]
Are you on the domogik 0.5-hotfix branch ?
If yes, this is "normal", I had to add a parameter (devices) to a function to improve the butler speed
You will need to use the last brain-base package when I will push it (this week end I hope)

Sorry for the disturbance :(

**Comment by overload08** [comment]
develop for brain and domogik too

**Comment by fritz-smh** [comment]
ah, so this is the other case :)
You updated brain-base from develop branch in the last 2/3 days ?

**Comment by overload08** [comment]
today :)

**Comment by fritz-smh** [comment]
the upgrade of the butler in 0.5-hotfix is not yet merged in develop.
You can switch back to the master branch of brain-base.

**Comment by overload08** [comment]
ok thanks

**Comment by fritz-smh** [comment]
You are welcome, I close.
